### ISSUE TITLE
bosh CPI error when using disk category 'cloud_ssd'

### ISSUE THREAD

**Issue by cloudyday** [cloudfoundry-incubator/bosh-alicloud-cpi-release#57] opened 2019-02-20 15:47 UTC
Hi,

using the following disk pool configuration, we get an error during the bosh deployment.
```
disk_pools:
- name: some-disk-pool
  disk_size: 20000
  cloud_properties:
    category: cloud_ssd
```

The error given by bosh shows that it cannot get the device path:
```
Error: Action Failed get_task: Task 596d76bf-6f7f-40eb-4b65-7319a92ce469 result: Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/xvdc
```

With `cloud_efficiency` this error does not show up.

I should mention that it is in fact about the "x" in the device name /dev/xvdc returned by bosh. Because the actual device name on the VM is /dev/vdc.

**CPI release version: v20**

Please investigate.
Kind regards
Oliver

## References
This might be a similar problem as in the terraform CPI.
https://github.com/terraform-providers/terraform-provider-alicloud/issues/781

**Comment by ala2208** [comment] 2019-03-21 13:30
Hi, 
I validated the new version v21 and it does not resolve the issue.
Pls fix it.

**Comment by xiaozhu36** [comment] 2019-03-21 16:02
HI @ala2208 Just now, I made a test using your case, and I can deploy bosh director successfully. Can you show me more details?

**Comment by xiaozhu36** [comment] 2019-03-22 11:40
HI @ala2208 When did this error occur? Deploying a new director or changing director disk size/category?

**Comment by ala2208** [comment] 2019-03-25 14:43
I got an error while changing director disk category.

**Comment by xiaozhu36** [comment] 2019-03-25 14:46
HI @ala2208 I am sorry to tell you that currently, the there is no API can support changing the disk category. Do you want to migrate the data by changing the data disk?

**Comment by alexwo** [comment] 2019-03-25 15:10
@xiaozhu36 
We must have an option to migrate between regular disk types to ssd.
This is documented in bosh:
https://bosh.io/docs/persistent-disks/#changing-persistent-disk

The CPI need to support bosh with correct disk mounts, bosh knows to migrate the disks.

will you have an option to test disk migration from regular disk to ssd, and fix CPI mounting issue in this flow?

**Comment by xiaozhu36** [comment] 2019-03-26 13:46
HI @ala2208 @alexwo As far as I know, currently, the native disk resize is not yet fully supported by the BOSH agent and there is a [known issue](https://www.pivotaltracker.com/n/projects/1456570/stories/161478343).  As workaround you can switch to the normal resize. Disabling  `director.enable_cpi_resize_disk` should switch this feature off. Please disable it and try again.

**Comment by alexwo** [comment] 2019-03-26 14:59
Hi @xiaozhu36 ,
The issue is reported on the openstack CPI impl, not related to bosh itself.
according to bosh docs and also to what we have tested, the disk resize works in Alicloud as well.
what currently seem to be the problem is only if we change disk type category from cloud efficiency to cloud ssd. 

if you mange to solve the mount point issue problem, I believe that bosh will be able to perform all the data migration part via the agent.

**Comment by xiaozhu36** [comment] 2019-03-27 01:26
HI @alexwo  Did you turn on `enable_cpi_resize_disk` ?

**Comment by cloudyday** [comment] 2019-04-14 11:34
Is there any progress on this one?

**Comment by xiaozhu36** [comment] 2019-04-17 08:18
HI @alexwo Ok, I will remove the current `resize_disk` implementation and it will be re-back after bosh director fix it.

**Comment by lemondlut** [comment] 2019-04-24 01:58
@alexwo , Could you provide manifest or other resources to help to reproduce your issue, please?

**Comment by alexwo** [comment] 2019-04-24 15:08
Please review the steps to reproduce this issue:

1.Have a cloud-config deployed with the following disk properties:
disk_types:
- name: disk_20G
  disk_size: 1024
  cloud_properties:
    encrypted: true

2. have a deployment manifest that reference this disk type as:
persistent_disk_type: disk_20G
(persistent_disk_type [String, optional]: A valid disk type name from the cloud config. Read more about persistent disks) 

3.Deploy this deployment with at least 1 vm that uses the persistent disk + verify that regular 20gb disk was created.

4.After deploying the vm with the above settings, we want to change the disk type in cloud config. Modify cloud-config settings to include the ssd disk change as:

- name: disk_20G
  disk_size: 20000
  cloud_properties:
    category: cloud_ssd
    encrypted: true

5. re-deploy bosh-cloud config after updating the settings
6 re-deploy the bosh deployment for the vm that uses this disk type

Expected result:
VM disk type changed to ssd disk type and all data that was in the original disk was migrated to the new ssd disk (by bosh)

Actual result:
Bosh fails to update the vm & deployment with this error:
Error: Action Failed get_task: Task 596d76bf-6f7f-40eb-4b65-7319a92ce469 result: Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/xvdc

**Comment by ala2208** [comment] 2019-05-01 16:03
Hi,

The latest version of bosh cpi fixes the issue.
So the issue can be closed.

**Closed** 2019-05-06 10:21 UTC
